### ISSUE TITLE
shared not available on windows? Or just not uploaded?

### ISSUE THREAD

**Issue by lilith** [lasote/conan-littlecms#1]
https://ci.appveyor.com/project/imazen/imageflow/build/1.0.240/job/cfbuyiv341wrw15h#L112

**Comment by lasote** [comment]
I'm excluding the windows shared packages, I don't remember exactly why, probably the compilation fails. I will take a look to it and see what happens with gcc 5.4 and fpic.

https://github.com/lasote/conan-littlecms/blob/master/build.py

**Comment by lasote** [comment]
I don't know why is failing with gcc 5.4, I can generate the packages with an example OK and it seems to be compiling it with -fPIC option.
I've checked your travis logs but it is caching the conan data directory so I can't see the littlecms compilation trace logs. I've uploaded 5.4 packages to conan.io, please try with now without caching them.

**Comment by lilith** [comment]
I clicked clear cache on travis, restarted, and the build passed! Thank you very much! I think this is resolved.

**Comment by lilith** [comment]
So this did fix travis, but not Windows/Appveyor.  

```
ARN: config() has been deprecated. Use config_options and configure
littlecms/2.7@lasote/stable: Not found, looking in remotes...
littlecms/2.7@lasote/stable: Trying with 'conan.io'...
Downloading conanmanifest.txt
[==================================================]                  
Downloading conanfile.py
[==================================================]                  
Downloading conan_export.tgz
[==================================================]                  
ERROR: littlecms/2.7@lasote/stable: 'options.shared' doesn't exist
'options' possible configurations are none
```

I'm reopening since the original issue remains (although you fixed travis!).

**Comment by lasote** [comment]
Hi! I patched the Cmakelist to support Windows DLL and uploaded the packages. please try now!

**Comment by lilith** [comment]
Thank you so much!
